before:
  hooks:
    - go mod tidy
builds:
  - id: intake-invoke
    binary: quetaro-intake-invoke
    main: ./cmd/intake-invoke
    ldflags:
      - -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
  - id: intake-pull
    binary: quetaro-intake-pull
    main: ./cmd/intake-pull
    ldflags:
      - -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
  - id: outlet-failure
    binary: quetaro-outlet-failure
    main: ./cmd/outlet-failure
    ldflags:
      - -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
  - id: outlet-success
    binary: quetaro-outlet-success
    main: ./cmd/outlet-success
    ldflags:
      - -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
checksum:
  name_template: "checksums.txt"
