name: test
on:
  pull_request:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        ports:
          - 15432:5432
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      localstack:
        image: localstack/localstack
        ports:
          - 4566:4566
        env:
          SERVICES: iam,lambda,logs,sqs
        options: >-
          --health-cmd "curl -f localhost:4566/_localstack/health | grep -q available"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: ">=1.19.4"
      - uses: hashicorp/setup-terraform@v3
      - uses: golangci/golangci-lint-action@v3
        with:
          args: -E misspell
      - run: make
      - run: terraform init && terraform apply -auto-approve
        working-directory: _etc/terraform
      - run: ./_etc/db/setup.sh
        env:
          PGDATABASE: qtr_test
      - run: make test
        env:
          TEST_QTR_DATABASE_DSN: postgres://qtr_test@localhost:15432
          TEST_AWS_ENDPOINT_URL: http://localhost:4566
